#ifndef _GLASS_BASE_CONSTANTS_H
#define _GLASS_BASE_CONSTANTS_H

#define GLASS_DECL_FLAG(id) (u32)(1u << (id))

#define GLASS_INVALID_OBJECT 0
#define GLASS_TEX_TARGET_UNBOUND 0

#define GLASS_NUM_ATTRIB_REGS 16
#define GLASS_MAX_ENABLED_ATTRIBS 12
#define GLASS_NUM_BOOL_UNIFORMS 16
#define GLASS_NUM_INT_UNIFORMS 4
#define GLASS_NUM_FLOAT_UNIFORMS 96
#define GLASS_NUM_COMBINER_STAGES 6
#define GLASS_NUM_TEX_UNITS 3
#define GLASS_MAX_FB_WIDTH 1024
#define GLASS_MAX_FB_HEIGHT 1024
#define GLASS_MIN_TEX_SIZE 8
#define GLASS_MAX_TEX_SIZE 1024
#define GLASS_NUM_TEX_LEVELS 8
#define GLASS_NUM_TEX_FACES 6

#define GLASS_UNI_BOOL 0x00
#define GLASS_UNI_INT 0x01
#define GLASS_UNI_FLOAT 0x02

#define GLASS_BUFFER_TYPE 0x01
#define GLASS_RENDERBUFFER_TYPE 0x02
#define GLASS_FRAMEBUFFER_TYPE 0x03
#define GLASS_PROGRAM_TYPE 0x04
#define GLASS_SHADER_TYPE 0x05
#define GLASS_TEXTURE_TYPE 0x06

#define GLASS_SHADER_FLAG_DELETE GLASS_DECL_FLAG(0)
#define GLASS_SHADER_FLAG_GEOMETRY GLASS_DECL_FLAG(1)
#define GLASS_SHADER_FLAG_MERGE_OUTMAPS GLASS_DECL_FLAG(2)
#define GLASS_SHADER_FLAG_USE_TEXCOORDS GLASS_DECL_FLAG(3)

#define GLASS_PROGRAM_FLAG_DELETE GLASS_DECL_FLAG(0)
#define GLASS_PROGRAM_FLAG_LINK_FAILED GLASS_DECL_FLAG(1)
#define GLASS_PROGRAM_FLAG_UPDATE_VERTEX GLASS_DECL_FLAG(2)
#define GLASS_PROGRAM_FLAG_UPDATE_GEOMETRY GLASS_DECL_FLAG(3)

#define GLASS_ATTRIB_FLAG_ENABLED GLASS_DECL_FLAG(0)
#define GLASS_ATTRIB_FLAG_FIXED GLASS_DECL_FLAG(1)

#define GLASS_CONTEXT_FLAG_FRAMEBUFFER GLASS_DECL_FLAG(0)
#define GLASS_CONTEXT_FLAG_DRAW GLASS_DECL_FLAG(1)
#define GLASS_CONTEXT_FLAG_VIEWPORT GLASS_DECL_FLAG(2)
#define GLASS_CONTEXT_FLAG_SCISSOR GLASS_DECL_FLAG(3)
#define GLASS_CONTEXT_FLAG_ATTRIBS GLASS_DECL_FLAG(4)
#define GLASS_CONTEXT_FLAG_PROGRAM GLASS_DECL_FLAG(5)
#define GLASS_CONTEXT_FLAG_COMBINERS GLASS_DECL_FLAG(6)
#define GLASS_CONTEXT_FLAG_FRAGOP GLASS_DECL_FLAG(7)
#define GLASS_CONTEXT_FLAG_DEPTHMAP GLASS_DECL_FLAG(8)
#define GLASS_CONTEXT_FLAG_COLOR_DEPTH GLASS_DECL_FLAG(9)
#define GLASS_CONTEXT_FLAG_EARLY_DEPTH GLASS_DECL_FLAG(10)
#define GLASS_CONTEXT_FLAG_EARLY_DEPTH_CLEAR GLASS_DECL_FLAG(11)
#define GLASS_CONTEXT_FLAG_STENCIL GLASS_DECL_FLAG(12)
#define GLASS_CONTEXT_FLAG_CULL_FACE GLASS_DECL_FLAG(13)
#define GLASS_CONTEXT_FLAG_ALPHA GLASS_DECL_FLAG(14)
#define GLASS_CONTEXT_FLAG_BLEND GLASS_DECL_FLAG(15)
#define GLASS_CONTEXT_FLAG_TEXTURE GLASS_DECL_FLAG(16)
#define GLASS_CONTEXT_FLAG_ALL (~(0u))

#endif /* _GLASS_BASE_CONSTANTS_H */